site_name: HIV52 – Levegger
site_description: >-
  Designgrunnlag for levegger mellom boligene i rekka Helge Ingstads vei 50-58,
  Boligsameiet Griniskogen Vest
site_url: https://storhaug-ting.github.io/HIV52-Levegg/
repo_name: Storhaug-ting/HIV52-Levegg
repo_url: https://github.com/Storhaug-ting/HIV52-Levegg

docs_dir: docs
site_dir: site

theme:
  name: material
  language: nb
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Følg systemets fargevalg
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/brightness-7
        name: Bytt til mørk modus
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/brightness-4
        name: Bytt til lys modus
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Oversikt: index.md
  - Designbeskrivelse: Designbeskrivelse.md
  - Byggeteknikk: Byggeteknikk.md
  - Regelverk: Regelverk.md
  - Kilder: Kilder.md
  - Naboerklæring: Naboerklaering.md
  - Avklaringer: Avklaringer.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
